num1=int(input("Enter the first number"))
num2=int(input("Enter the second number"))
print("Both are equal=",num1==num2)
print("First number is great=",num1>num2)
print("Second number is greater than First=",num2>num1)
